spring.application.name=funworld
spring.datasource.url=jdbc:h2:mem:funworlddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
server.port=8080
spring.data.mongodb.uri=mongodb+srv://funworld:Manfun%40321@cluster0.gc9aape.mongodb.net/funworld?retryWrites=true&w=majority&appName=Cluster0
